env:
  global:
    - PROJECT_NAME=oficina-virtual
    # master SHA256-606c78f9bd55e946b34762b7f54b65177eaa37a3fc42559ea62712cf30431b2b
    #- secure: 
    # beta SHA256-af7507b9411c78ff3df1efd621fbcb9ec9ab7057af1aa1e543dbca6a9c4020f0
    - secure: "BuHgW8A3IPejEAu2GK/l5rVnfzEqMrFVCuNLM8tiofUjhrI7POzb3wne6qi0TfFCcROta+hvpgw0pMZPMmxkPA+2lJ0RiAPY7bDiXDu9Jrr1jCDOOh/rVIFI0M4iZDMZfzqo+XtP80AeSrn5aRjLsz1GIGqNqezRXe6FpNp+/BKlqh3Pre3kSsoqXoYxYH7Q2HqitEzYy7h+4mycHjYsuMbnZahAw0UcwUtCiz5CUmnNVqEetHRr8TNQKDbZmC9nAr20yRHNLgLIADMkfvMxBazKcOhMJDMaHy6V1K8asu0IblrNCPp4ZQmHWN+W0U2cNJHEFxMEKJssxsXtaQ9iQ6hdIe1mDeiaCIn23hxwAKfzhFHXIx/NJCg63FCXWfQoCy7DrkNGd3SFMJS3m+IvvYTlsLr01kB4DYsfHhHBFz0oP0YNMccUqBCDzg71Mv65f6+jm2WfNXNzf051mbXSWabfqtEesynrdjoY+MAFheGav2nJgB7K+FqRkJDgj0AZVeDWvt3FFMC/IIMlABtuUfL4sLQ3/NoEYxv8zExqmVqhjNk4DUkFzDbz9XEiACoojZi8kkZZyRQSnpKE2J/9TE5vO8XJsOgn30T0HlV/2eDyIdu2cUEwC0UVvpT7XJ6D+sS/JrogOgxzm8s7dWdZg5axr9oJ8FTFumAXABRYIDc="
  - true
notifications:
  email: false
language: node_js
node_js:
  - "6"
before_deploy:
  - 'git config --global user.email "deploy@travis-ci"'
  - 'git config --global user.name "[Deploy]"'
  - export GIT_FTP_URL_BRANCH=GIT_FTP_URL_$TRAVIS_BRANCH
  - './git-ftp add-scope $TRAVIS_BRANCH "${!GIT_FTP_URL_BRANCH}"'
  - git config git-ftp.syncroot public
deploy:
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: beta