env:
  global:
    - PROJECT_NAME=oficina-virtual
    # master SHA256-606c78f9bd55e946b34762b7f54b65177eaa37a3fc42559ea62712cf30431b2b
    - secure: ""
    # beta SHA256-af7507b9411c78ff3df1efd621fbcb9ec9ab7057af1aa1e543dbca6a9c4020f0
    # secure: ""
script:
  - true
notifications:
  email: false
language: node_js
node_js:
  - "6"
before_deploy:
  - 'git config --global user.email "deploy@travis-ci"'
  - 'git config --global user.name "[Deploy]"'
  - export GIT_FTP_URL_BRANCH=GIT_FTP_URL_$TRAVIS_BRANCH
  - './git-ftp add-scope $TRAVIS_BRANCH "${!GIT_FTP_URL_BRANCH}"'
  - git config git-ftp.syncroot public
  - npm install -g uglify-js
  - gem install sass -v 3.4.23 --no-ri --no-rdoc
deploy:
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: beta