env:
  global:
    - PROJECT_NAME=oficina-virtual
    # master SHA256-606c78f9bd55e946b34762b7f54b65177eaa37a3fc42559ea62712cf30431b2b
    #- secure: 
    # beta SHA256-af7507b9411c78ff3df1efd621fbcb9ec9ab7057af1aa1e543dbca6a9c4020f0
    - secure: "bcbXaOiU0P9q0LlQGUtHCVOzrpf+beFDhVI3Yu2cXppBEP4mo9HnjdwxSsUfmqPsvkbd4NljX2siKexkEdpo2fzY6ZJgoxvA5fUVT9d9V4V4E7xNwB12ERSHe6Mz8TlI+robbdNlr1uVvKylSswifPOzEV2pgiyqS2UQTzmN8M7pacsoTVCIC2SbuVUKeyFYsiu1lzzJSM7lcfjh8QUnDqM/nYdK0sRGv88gpvJOdmCYdGtLqo8LL5Oa/p7os1qxWeOb1L8S6Ug6Yy4G63AsdZhadmdyZnEa6J5aebCpLles2kwErPFAocCb9B5VkRVUU9GkllGHxhyOojHIF2BvE0+zNLcqGRnZ12/fA9Dngn/gumOFhYiS5i1eV/xmkAmxYjzTqnsau41ezMvUgRo3BqkfoNFVfIGhmVGpFAel8au+JzGWa84MYeFpCOrFhfxQUzhK2UBgOzF2Wd9kESA9RrFyV50g00O4uWust3dGTXyekugJzPXBrq2/xuFyhJsq25q+Vyxm92koyWr892e+BAXua0gVcpby60HIE5V/QIGrjti7uQDiWXWUjZb6jDd8vqyLQVt+CHcQkdaSynOt+lTKrbPJ1LI0LCGH+sxfPCPFfiBQmAmDcMzMnUTRLsi1n88JjKJmVj8TSgRLw76NGlJp5A2iwP1yw502nZyLsyM="
  - true
notifications:
  email: false
language: node_js
node_js:
  - "6"
before_deploy:
  - 'git config --global user.email "deploy@travis-ci"'
  - 'git config --global user.name "[Deploy]"'
  - export GIT_FTP_URL_BRANCH=GIT_FTP_URL_$TRAVIS_BRANCH
  - './git-ftp add-scope $TRAVIS_BRANCH "${!GIT_FTP_URL_BRANCH}"'
  - git config git-ftp.syncroot public
deploy:
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: beta